/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2019 MediaTek Inc.
*/
#ifndef __TZBATT_INITCFG_H__
#define __TZBATT_INITCFG_H__

#define TZBATT_SET_INIT_CFG				(1)

#define TZBATT_INITCFG_INTERVAL				(1)
#define TZBATT_INITCFG_NUM_TRIPS			(3)

#define TZBATT_INITCFG_TRIP_0_TEMP			(47000)
#define TZBATT_INITCFG_TRIP_0_COOLER			"mtk-cl-bcct02"

#define TZBATT_INITCFG_TRIP_1_TEMP			(46000)
#define TZBATT_INITCFG_TRIP_1_COOLER			"mtk-cl-bcct01"

#define TZBATT_INITCFG_TRIP_2_TEMP			(45000)
#define TZBATT_INITCFG_TRIP_2_COOLER			"mtk-cl-bcct00"

#define TZBATT_INITCFG_TRIP_3_TEMP			(41000)
#define TZBATT_INITCFG_TRIP_3_COOLER			""

#define TZBATT_INITCFG_TRIP_4_TEMP			(40000)
#define TZBATT_INITCFG_TRIP_4_COOLER			""

#define TZBATT_INITCFG_TRIP_5_TEMP			(39000)
#define TZBATT_INITCFG_TRIP_5_COOLER			""

#define TZBATT_INITCFG_TRIP_6_TEMP			(38000)
#define TZBATT_INITCFG_TRIP_6_COOLER			""

#define TZBATT_INITCFG_TRIP_7_TEMP			(37000)
#define TZBATT_INITCFG_TRIP_7_COOLER			""

#define TZBATT_INITCFG_TRIP_8_TEMP			(36000)
#define TZBATT_INITCFG_TRIP_8_COOLER			""

#define TZBATT_INITCFG_TRIP_9_TEMP			(35000)
#define TZBATT_INITCFG_TRIP_9_COOLER			""

#endif	/* __TZBATT_INITCFG_H__ */
